[tools]
# Core
node = "lts"
pnpm = "latest"

# Build
"npm:prettier" = "latest"
"npm:@typescript/native-preview" = "latest"
"npm:wrangler" = "latest"
"npm:astro" = "^5.13.5"

# Develop
"npm:@openai/codex" = "latest"

[tasks]
dev = "astro dev"
build = "astro build"
preview = "astro preview"
fmt = "prettier --write ."

[tasks.typecheck]
description = "Typecheck the entire project"
depends = "typegen:*"
run = "tsgo --noEmit"

[tasks."typegen:cloudflare"]
description = "Generate types for Cloudflare bindings"
sources = ["wrangler.jsonc"]
outputs = ["worker-configuration.d.ts"]
run = "wrangler types"

[tasks.postinstall]
description = "Generate types after npm package installation"
run = """
  if [ -z \"$GITHUB_ACTIONS\" ]; then
    mise run "typegen:*"
  else
    echo '✅ Skipping typegen in CI'
  fi
"""
