[tools]
# Core
node = "lts"
pnpm = "latest"

# Build
"npm:prettier" = "latest"
"npm:@typescript/native-preview" = "latest"
"npm:wrangler" = "latest"
"npm:astro" = "^5.13.5"

# Develop
"npm:@openai/codex" = "latest"

[tasks]
dev = "astro dev"
build = "astro build"
preview = "astro preview"
fmt = "prettier --write ."
typecheck = "tsgo --noEmit"
